version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo "Pre build"
      - git checkout release
      - git pull origin release
      - pip3 install pyinstaller
      - python.exe -m pip install -U setuptools
      - pip3 install --upgrade -r requirements.txt
      - pip3 install ./vendor/SDK/
      - mkdir keys
      - aws s3 cp s3://dshc-public/PUBLIC_key.pem ./keys
  build:
    commands:
      - echo "Building"         
      - pyinstaller.exe -F extractor.py  --icon=tmlogo.ico
      # --hidden-import=pkg_resources.py2_warn --hidden-import=deepsecurity -p c:\python37\lib\site-packages\requests -p c:\python37\lib\site-packages\colorama
  post_build:
    commands:
      - echo "Post build"
      - python.exe utils/gen_config.py
      - mkdir dist/keys
      - cp keys/* dist/keys
      - mkdir dist/config
      - cp config/api_config.yml dist/config/
      - cp docs/EXTRACTOR_README.md dist/
      - powershell.exe ./utils/zip_extractor_windows.ps1
      - aws s3 cp extractor-windows.zip s3://dshc-public/extractors/

        
      
