version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo "Pre build"
      - git checkout release
      - git pull origin release
      - pip3 install pyinstaller
      - pip3 install --upgrade -r requirements.txt
      - pip3 install ./vendor/SDK/
      - mkdir keys
      - aws s3 cp s3://dshc-public/PUBLIC_key.pem ./keys 
  build:
    commands:
      - echo "Building"         
      - pyinstaller -F extractor.py
      # --hidden-import=pkg_resources.py2_warn -p /usr/local/lib/python3.7/dist-packages/deepsecurity/ -p /usr/local/lib/python3.7/dist-packages/colorama/ -p /usr/local/lib/python3.7/dist-packages/requests/ 
  post_build:
    commands:
      - echo "Post build"
      - python3 utils/gen_config.py
      - zip extractor-linux.zip -j dist/extractor docs/EXTRACTOR_README.md
      - zip extractor-linux.zip extractor config/api_config.yml keys/PUBLIC_key.pem
      - aws s3 cp extractor-linux.zip s3://dshc-public/extractors/

        
      
